FROM nvcr.io/nvidia/pytorch:20.10-py3

# Install linux packages
RUN apt update && apt install -y screen

ENV CELERY_BROKER_URL redis://redis:6379/0
ENV CELERY_RESULT_BACKEND redis://redis:6379/0
ENV C_FORCE_ROOT true
ENV PYTHONOPTIMIZE 1
COPY . /queue
WORKDIR /queue

# RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pip -U
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple

RUN pip install  -r requirements.txt

# production
#ENTRYPOINT celery -A tasks worker --loglevel=info

# hot code reloading
ENTRYPOINT watchmedo auto-restart --directory=./ --pattern=*.py --recursive -- celery -A tasks worker --concurrency=5 --loglevel=INFO   -n socwebai #--beat

